/* Generated by tools/generate_static_art.py; do not edit. */
#pragma once

#include <stdint.h>

#define PJ_DEFAULT_STATIC_ART_WIDTH 200
#define PJ_DEFAULT_STATIC_ART_HEIGHT 200
#define PJ_DEFAULT_STATIC_ART_BYTES 5000
#define PJ_DEFAULT_STATIC_ART_THRESHOLD 128
#define PJ_DEFAULT_STATIC_ART_BLACK_PIXELS 27864
#define PJ_DEFAULT_STATIC_ART_SOURCE_SHA256 "ef0fb9a1a2764e19d04056ee57bf9af0c86c2baba2aae098ed945dc07c0d4e9d"
#define PJ_DEFAULT_STATIC_ART_PACKED_SHA256 "c17094c7335ee169ee79a544d1db9e7c061bfb8318130fcc4c82f12768f00df5"

extern const uint8_t pj_default_static_art[PJ_DEFAULT_STATIC_ART_BYTES];
