// Generated by tools/generate_dxf_geometry.py. Do not edit.
#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define PJ_LAYOUT_DISPLAY_WIDTH 200u
#define PJ_LAYOUT_DISPLAY_HEIGHT 200u
#define PJ_LAYOUT_COORD_SCALE 16
#define PJ_LAYOUT_RULE_WIDTH_PX 4u

typedef enum {
    PJ_LAYOUT_HOME_3_1 = 0,
    PJ_LAYOUT_NOTES_3_1M = 1,
    PJ_LAYOUT_TIME_4_1 = 2,
    PJ_LAYOUT_SETTINGS_4_0M = 3,
    PJ_LAYOUT_COUNT = 4,
} pj_layout_id_t;

typedef enum {
    PJ_LAYOUT_SLOT_NONE = 0,
    PJ_LAYOUT_SLOT_HOME_TIME = 1,
    PJ_LAYOUT_SLOT_HOME_NOTES = 2,
    PJ_LAYOUT_SLOT_HOME_SETTINGS = 3,
    PJ_LAYOUT_SLOT_NOTES_RECORD = 4,
    PJ_LAYOUT_SLOT_NOTES_LISTEN = 5,
    PJ_LAYOUT_SLOT_NOTES_READ = 6,
    PJ_LAYOUT_SLOT_TIME_ALARM = 7,
    PJ_LAYOUT_SLOT_TIME_STOPWATCH = 8,
    PJ_LAYOUT_SLOT_TIME_TIMER = 9,
    PJ_LAYOUT_SLOT_TIME_INTERVAL = 10,
    PJ_LAYOUT_SLOT_SETTINGS_VOLUME = 11,
    PJ_LAYOUT_SLOT_SETTINGS_THEME = 12,
    PJ_LAYOUT_SLOT_SETTINGS_HOUR_FORMAT = 13,
    PJ_LAYOUT_SLOT_SETTINGS_SYNC = 14,
    PJ_LAYOUT_SLOT_COUNT = 15,
} pj_layout_slot_id_t;

typedef struct {
    int16_t x;
    int16_t y;
} pj_layout_point_t;

typedef struct {
    pj_layout_point_t start;
    pj_layout_point_t end;
} pj_layout_rule_t;

typedef struct {
    const pj_layout_point_t *vertices;
    uint8_t vertex_count;
} pj_layout_polygon_t;

typedef struct {
    pj_layout_slot_id_t id;
    pj_layout_point_t icon_center;
    pj_layout_polygon_t hit_region;
} pj_layout_slot_t;

typedef struct {
    pj_layout_id_t id;
    const pj_layout_rule_t *rules;
    const pj_layout_slot_t *slots;
    uint8_t rule_count;
    uint8_t slot_count;
} pj_layout_geometry_t;

const pj_layout_geometry_t *pj_layout_geometry(pj_layout_id_t layout_id);
pj_layout_slot_id_t pj_layout_hit_test(pj_layout_id_t layout_id, uint16_t x, uint16_t y);
bool pj_layout_pixel_is_rule(pj_layout_id_t layout_id, uint16_t x, uint16_t y);

#ifdef __cplusplus
}
#endif
