// Generated by tools/generate_dxf_geometry.py. Do not edit.
// 3_1.dxf: sha256 9382fb6d92f567473fae90817e5a1ecd708d249c920a75f50ad415c2ddd55aee
// 3_1m.dxf: sha256 a3db6f8a152f2f868b3ec5be1325974d9f92d7665e1857c1541b70772ee432ae
// 4_1.dxf: sha256 ba0cba4e59edfa718466eec60f5b69fd40f718d177986710c9590f1fc9001ea8
// 4_0m.dxf: sha256 608863e99b81cc76da1599850615a9f81a8f6460de3389f87e7fcc5eb560d50b
#include "pj_layout_geometry.h"

#include <stdint.h>

static const pj_layout_rule_t HOME_3_1_RULES[] = {
    {{1600, 1600}, {3200, 2503}},
    {{1600, 1600}, {0, 3040}},
    {{1600, 1600}, {1135, 0}}
};

static const pj_layout_point_t HOME_3_1_SLOT_0_POLYGON[] = {{0, 0}, {1135, 0}, {1600, 1600}, {0, 3040}};

static const pj_layout_point_t HOME_3_1_SLOT_1_POLYGON[] = {{1600, 1600}, {3200, 2503}, {3200, 3200}, {0, 3200}, {0, 3040}};

static const pj_layout_point_t HOME_3_1_SLOT_2_POLYGON[] = {{1135, 0}, {3200, 0}, {3200, 2503}, {1600, 1600}};

static const pj_layout_slot_t HOME_3_1_SLOTS[] = {
    {PJ_LAYOUT_SLOT_HOME_TIME, {636, 1271}, {HOME_3_1_SLOT_0_POLYGON, (uint8_t)(sizeof(HOME_3_1_SLOT_0_POLYGON) / sizeof(HOME_3_1_SLOT_0_POLYGON[0]))}},
    {PJ_LAYOUT_SLOT_HOME_NOTES, {1741, 2625}, {HOME_3_1_SLOT_1_POLYGON, (uint8_t)(sizeof(HOME_3_1_SLOT_1_POLYGON) / sizeof(HOME_3_1_SLOT_1_POLYGON[0]))}},
    {PJ_LAYOUT_SLOT_HOME_SETTINGS, {2356, 990}, {HOME_3_1_SLOT_2_POLYGON, (uint8_t)(sizeof(HOME_3_1_SLOT_2_POLYGON) / sizeof(HOME_3_1_SLOT_2_POLYGON[0]))}}
};

static const pj_layout_rule_t NOTES_3_1M_RULES[] = {
    {{1600, 1600}, {1135, 3200}},
    {{1600, 1600}, {0, 160}},
    {{1600, 1600}, {3200, 697}}
};

static const pj_layout_point_t NOTES_3_1M_SLOT_0_POLYGON[] = {{0, 0}, {3200, 0}, {3200, 697}, {1600, 1600}, {0, 160}};

static const pj_layout_point_t NOTES_3_1M_SLOT_1_POLYGON[] = {{0, 160}, {1600, 1600}, {1135, 3200}, {0, 3200}};

static const pj_layout_point_t NOTES_3_1M_SLOT_2_POLYGON[] = {{3200, 697}, {3200, 3200}, {1135, 3200}, {1600, 1600}};

static const pj_layout_slot_t NOTES_3_1M_SLOTS[] = {
    {PJ_LAYOUT_SLOT_NOTES_RECORD, {1741, 575}, {NOTES_3_1M_SLOT_0_POLYGON, (uint8_t)(sizeof(NOTES_3_1M_SLOT_0_POLYGON) / sizeof(NOTES_3_1M_SLOT_0_POLYGON[0]))}},
    {PJ_LAYOUT_SLOT_NOTES_LISTEN, {636, 1929}, {NOTES_3_1M_SLOT_1_POLYGON, (uint8_t)(sizeof(NOTES_3_1M_SLOT_1_POLYGON) / sizeof(NOTES_3_1M_SLOT_1_POLYGON[0]))}},
    {PJ_LAYOUT_SLOT_NOTES_READ, {2356, 2210}, {NOTES_3_1M_SLOT_2_POLYGON, (uint8_t)(sizeof(NOTES_3_1M_SLOT_2_POLYGON) / sizeof(NOTES_3_1M_SLOT_2_POLYGON[0]))}}
};

static const pj_layout_rule_t TIME_4_1_RULES[] = {
    {{1515, 1685}, {1688, 3200}},
    {{1685, 1515}, {3200, 1688}},
    {{1515, 1685}, {0, 1512}},
    {{1685, 1515}, {1515, 1685}},
    {{1685, 1515}, {1512, 0}}
};

static const pj_layout_point_t TIME_4_1_SLOT_0_POLYGON[] = {{0, 0}, {1512, 0}, {1685, 1515}, {1515, 1685}, {0, 1512}};

static const pj_layout_point_t TIME_4_1_SLOT_1_POLYGON[] = {{1512, 0}, {3200, 0}, {3200, 1688}, {1685, 1515}};

static const pj_layout_point_t TIME_4_1_SLOT_2_POLYGON[] = {{0, 1512}, {1515, 1685}, {1688, 3200}, {0, 3200}};

static const pj_layout_point_t TIME_4_1_SLOT_3_POLYGON[] = {{1685, 1515}, {3200, 1688}, {3200, 3200}, {1688, 3200}, {1515, 1685}};

static const pj_layout_slot_t TIME_4_1_SLOTS[] = {
    {PJ_LAYOUT_SLOT_TIME_ALARM, {815, 815}, {TIME_4_1_SLOT_0_POLYGON, (uint8_t)(sizeof(TIME_4_1_SLOT_0_POLYGON) / sizeof(TIME_4_1_SLOT_0_POLYGON[0]))}},
    {PJ_LAYOUT_SLOT_TIME_STOPWATCH, {2414, 786}, {TIME_4_1_SLOT_1_POLYGON, (uint8_t)(sizeof(TIME_4_1_SLOT_1_POLYGON) / sizeof(TIME_4_1_SLOT_1_POLYGON[0]))}},
    {PJ_LAYOUT_SLOT_TIME_TIMER, {786, 2414}, {TIME_4_1_SLOT_2_POLYGON, (uint8_t)(sizeof(TIME_4_1_SLOT_2_POLYGON) / sizeof(TIME_4_1_SLOT_2_POLYGON[0]))}},
    {PJ_LAYOUT_SLOT_TIME_INTERVAL, {2385, 2385}, {TIME_4_1_SLOT_3_POLYGON, (uint8_t)(sizeof(TIME_4_1_SLOT_3_POLYGON) / sizeof(TIME_4_1_SLOT_3_POLYGON[0]))}}
};

static const pj_layout_rule_t SETTINGS_4_0M_RULES[] = {
    {{1685, 1685}, {1512, 3200}},
    {{1515, 1515}, {0, 1688}},
    {{1515, 1515}, {1685, 1685}},
    {{1685, 1685}, {3200, 1512}},
    {{1515, 1515}, {1688, 0}}
};

static const pj_layout_point_t SETTINGS_4_0M_SLOT_0_POLYGON[] = {{0, 0}, {1688, 0}, {1515, 1515}, {0, 1688}};

static const pj_layout_point_t SETTINGS_4_0M_SLOT_1_POLYGON[] = {{1688, 0}, {3200, 0}, {3200, 1512}, {1685, 1685}, {1515, 1515}};

static const pj_layout_point_t SETTINGS_4_0M_SLOT_2_POLYGON[] = {{1515, 1515}, {1685, 1685}, {1512, 3200}, {0, 3200}, {0, 1688}};

static const pj_layout_point_t SETTINGS_4_0M_SLOT_3_POLYGON[] = {{3200, 1512}, {3200, 3200}, {1512, 3200}, {1685, 1685}};

static const pj_layout_slot_t SETTINGS_4_0M_SLOTS[] = {
    {PJ_LAYOUT_SLOT_SETTINGS_VOLUME, {786, 786}, {SETTINGS_4_0M_SLOT_0_POLYGON, (uint8_t)(sizeof(SETTINGS_4_0M_SLOT_0_POLYGON) / sizeof(SETTINGS_4_0M_SLOT_0_POLYGON[0]))}},
    {PJ_LAYOUT_SLOT_SETTINGS_THEME, {2385, 815}, {SETTINGS_4_0M_SLOT_1_POLYGON, (uint8_t)(sizeof(SETTINGS_4_0M_SLOT_1_POLYGON) / sizeof(SETTINGS_4_0M_SLOT_1_POLYGON[0]))}},
    {PJ_LAYOUT_SLOT_SETTINGS_HOUR_FORMAT, {815, 2385}, {SETTINGS_4_0M_SLOT_2_POLYGON, (uint8_t)(sizeof(SETTINGS_4_0M_SLOT_2_POLYGON) / sizeof(SETTINGS_4_0M_SLOT_2_POLYGON[0]))}},
    {PJ_LAYOUT_SLOT_SETTINGS_SYNC, {2414, 2414}, {SETTINGS_4_0M_SLOT_3_POLYGON, (uint8_t)(sizeof(SETTINGS_4_0M_SLOT_3_POLYGON) / sizeof(SETTINGS_4_0M_SLOT_3_POLYGON[0]))}}
};

static const pj_layout_geometry_t GEOMETRIES[] = {
    {PJ_LAYOUT_HOME_3_1, HOME_3_1_RULES, HOME_3_1_SLOTS, (uint8_t)(sizeof(HOME_3_1_RULES) / sizeof(HOME_3_1_RULES[0])), (uint8_t)(sizeof(HOME_3_1_SLOTS) / sizeof(HOME_3_1_SLOTS[0]))},
    {PJ_LAYOUT_NOTES_3_1M, NOTES_3_1M_RULES, NOTES_3_1M_SLOTS, (uint8_t)(sizeof(NOTES_3_1M_RULES) / sizeof(NOTES_3_1M_RULES[0])), (uint8_t)(sizeof(NOTES_3_1M_SLOTS) / sizeof(NOTES_3_1M_SLOTS[0]))},
    {PJ_LAYOUT_TIME_4_1, TIME_4_1_RULES, TIME_4_1_SLOTS, (uint8_t)(sizeof(TIME_4_1_RULES) / sizeof(TIME_4_1_RULES[0])), (uint8_t)(sizeof(TIME_4_1_SLOTS) / sizeof(TIME_4_1_SLOTS[0]))},
    {PJ_LAYOUT_SETTINGS_4_0M, SETTINGS_4_0M_RULES, SETTINGS_4_0M_SLOTS, (uint8_t)(sizeof(SETTINGS_4_0M_RULES) / sizeof(SETTINGS_4_0M_RULES[0])), (uint8_t)(sizeof(SETTINGS_4_0M_SLOTS) / sizeof(SETTINGS_4_0M_SLOTS[0]))}
};

static bool point_on_segment(pj_layout_point_t point, pj_layout_point_t first,
                             pj_layout_point_t second)
{
    int64_t cross = (int64_t)(point.x - first.x) * (second.y - first.y) -
                    (int64_t)(point.y - first.y) * (second.x - first.x);
    return cross == 0 && point.x >= (first.x < second.x ? first.x : second.x) &&
           point.x <= (first.x > second.x ? first.x : second.x) &&
           point.y >= (first.y < second.y ? first.y : second.y) &&
           point.y <= (first.y > second.y ? first.y : second.y);
}

static bool point_in_polygon(pj_layout_point_t point, const pj_layout_polygon_t *polygon)
{
    bool inside = false;
    for (uint8_t index = 0; index < polygon->vertex_count; index++) {
        pj_layout_point_t first = polygon->vertices[index];
        pj_layout_point_t second = polygon->vertices[(uint8_t)((index + 1u) % polygon->vertex_count)];
        if (point_on_segment(point, first, second)) {
            return true;
        }
        if ((first.y > point.y) == (second.y > point.y)) {
            continue;
        }
        int64_t left = (int64_t)(point.x - first.x) * (second.y - first.y);
        int64_t right = (int64_t)(point.y - first.y) * (second.x - first.x);
        if (((second.y > first.y) && (left < right)) ||
            ((second.y < first.y) && (left > right))) {
            inside = !inside;
        }
    }
    return inside;
}

static bool point_within_rule(pj_layout_point_t point, const pj_layout_rule_t *rule)
{
    int64_t vx = rule->end.x - rule->start.x;
    int64_t vy = rule->end.y - rule->start.y;
    int64_t wx = point.x - rule->start.x;
    int64_t wy = point.y - rule->start.y;
    int64_t length_squared = vx * vx + vy * vy;
    int64_t projection = wx * vx + wy * vy;
    const int64_t radius = (PJ_LAYOUT_RULE_WIDTH_PX * PJ_LAYOUT_COORD_SCALE) / 2;
    const int64_t radius_squared = radius * radius;

    if (projection <= 0) {
        return wx * wx + wy * wy <= radius_squared;
    }
    if (projection >= length_squared) {
        int64_t dx = point.x - rule->end.x;
        int64_t dy = point.y - rule->end.y;
        return dx * dx + dy * dy <= radius_squared;
    }
    int64_t cross = wx * vy - wy * vx;
    return cross * cross <= radius_squared * length_squared;
}

const pj_layout_geometry_t *pj_layout_geometry(pj_layout_id_t layout_id)
{
    if ((unsigned)layout_id >= PJ_LAYOUT_COUNT) {
        return NULL;
    }
    return &GEOMETRIES[layout_id];
}

pj_layout_slot_id_t pj_layout_hit_test(pj_layout_id_t layout_id, uint16_t x, uint16_t y)
{
    const pj_layout_geometry_t *geometry = pj_layout_geometry(layout_id);
    if (geometry == NULL || x >= PJ_LAYOUT_DISPLAY_WIDTH || y >= PJ_LAYOUT_DISPLAY_HEIGHT) {
        return PJ_LAYOUT_SLOT_NONE;
    }
    pj_layout_point_t point = {
        (int16_t)(x * PJ_LAYOUT_COORD_SCALE + PJ_LAYOUT_COORD_SCALE / 2),
        (int16_t)(y * PJ_LAYOUT_COORD_SCALE + PJ_LAYOUT_COORD_SCALE / 2),
    };
    for (uint8_t index = 0; index < geometry->slot_count; index++) {
        if (point_in_polygon(point, &geometry->slots[index].hit_region)) {
            return geometry->slots[index].id;
        }
    }
    return PJ_LAYOUT_SLOT_NONE;
}

bool pj_layout_pixel_is_rule(pj_layout_id_t layout_id, uint16_t x, uint16_t y)
{
    const pj_layout_geometry_t *geometry = pj_layout_geometry(layout_id);
    if (geometry == NULL || x >= PJ_LAYOUT_DISPLAY_WIDTH || y >= PJ_LAYOUT_DISPLAY_HEIGHT) {
        return false;
    }
    pj_layout_point_t point = {
        (int16_t)(x * PJ_LAYOUT_COORD_SCALE + PJ_LAYOUT_COORD_SCALE / 2),
        (int16_t)(y * PJ_LAYOUT_COORD_SCALE + PJ_LAYOUT_COORD_SCALE / 2),
    };
    for (uint8_t index = 0; index < geometry->rule_count; index++) {
        if (point_within_rule(point, &geometry->rules[index])) {
            return true;
        }
    }
    return false;
}
